services:
  mariadb:
    image: mariadb:11
    container_name: playgrounds-db
    env_file:
      - .env_db
    volumes:
      - ./db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - traefik-net

  playgrounds:
    container_name: playgrounds
    build: .
    image: playgrounds:latest
    depends_on:
      mariadb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - 8050:8050
    volumes:
      - ./src:/src
    env_file:
      - .env_app
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.playgrounds.rule=Host(`playgrounds.mirai.local`)"
      - "traefik.http.routers.playgrounds.entrypoints=web"
      - "traefik.http.services.playgrounds.loadbalancer.server.port=8050"

networks:
  traefik-net:
    external: true

volumes:
  mariadb-data:
